### ISSUE TITLE
能否支持snapToGrid功能

### ISSUE THREAD

**Issue by bbfpl** [vangleer/es-drager#1]
能否支持snapToGrid功能 类似https://kirillmurashov.com/vue-drag-resize/里面开启 snapToGrid效果

**Comment by vangleer** [comment]
现在还没有，看啥时候加一下

**Comment by vangleer** [comment]
snapToGrid 已支持，[examples 在线示例](https://vangleer.github.io/es-drager)，关一下issue哈，谢谢

**Comment by bbfpl** [comment]
牛逼
