### ISSUE TITLE
开启了边界判断，调整大小时会超出边界。

### ISSUE THREAD

**Issue by 75835234** [vangleer/es-drager#14]
`<div style="border: 1px solid red; position: relative; width: 400px; height: 600px;">
                <es-drager :width="100" :height="100" :equalProportion="true" :rotatable="true" :boundary="true" @click="layerClick">
                    drager
                </es-drager>
            </div>`
![GIF 2023-9-7 10-55-57](https://github.com/vangleer/es-drager/assets/125853439/e0a2ea94-ca41-437b-b875-7191efb2a56f)
**开启了边界判断，调整大小时会超出边界。应当像拖动那样，限定在框框里。另外属性建议加上maxWidth、maxHeight**

**Comment by vangleer** [comment]
The issue has been resolved. Please update `es-drager` to version `1.1.8`.
