### ISSUE TITLE
在设置缩放比scaleRatio并开启父级检测的情况下发生异常

### ISSUE THREAD

**Issue by djymike** [vangleer/es-drager#17]
拖动正常可以覆盖整个父级元素，但改变大小时无法覆盖整个父级区域，肉眼观察只可在不设置scaleRatio时的大小区域缩放，你的示例网站也可直接复现这个问题

**Comment by djymike** [comment]
还有个问题，设置缩放比例后且检测父元素后，再旋转，拖动到边界，会有部分出边界

**Comment by djymike** [comment]
第一个问题，在源码输出边界的方法里面，父元素宽高也除以比例后正常了，第二个问题暂时没时间找了
![image](https://github.com/vangleer/es-drager/assets/25447833/d18f8d20-cdc4-4899-80c0-97d715d499f2)

**Comment by vangleer** [comment]
老铁有兴趣可以试着解决一下，提个pr哈
