### ISSUE TITLE
希望提供scale参数实现缩放比列调整

### ISSUE THREAD

**Issue by bbfpl** [vangleer/es-drager#2]
基本信息:
在用于低代码大屏可视化平台开发过程中发现有一个场景，画布原本大小是1920*800 ，
当前会做一个获取缩放比例,然后把缩放比例传给es-drager，实现拖动距离一致。

现有案例：
https://gausszhou.github.io/vue-drag-resize-rotate/#/basic/basic-with-scale

预期解决问题:
缩放后实现拖动距离一致

**Comment by vangleer** [comment]
已实现，关一下，谢谢

**Comment by bbfpl** [comment]
大佬牛逼
