### ISSUE TITLE
Community: Request: 开启网格，缩放没有跟网格对齐

### ISSUE THREAD

**Issue by kafeibei001** [vangleer/es-drager#23]
Community: Request: 开启网格，缩放没有跟网格对齐-；
-- 
question：比如默认网格50 50  ，而给的拖动 div 默认90 90 ，那么默认左上角是对齐网格而言的，右边（下边）永远差10个像素（50 + 50 - 90）
这样总是感觉很奇怪（强迫症要被逼疯）-；
1、能不能给定一个属性，在开启网格的时候，缩放一定跟网格的距离对齐？，或者说是有其他解决方案-；
2、旋转属性可不可以添加旋转刻度（虽然好像没啥用）-；

**Comment by huccct** [comment]
好的，收到反馈，后续处理一下~

**Comment by vangleer** [comment]
这个问题感觉目前没有实现的必要，如果开启了网格，盒子的初始大小设置成网格大小倍数就行。后面缩放都会按照网格大小进行缩放

**Comment by vangleer** [comment]
开启网格后，初始大小和位置应该是能够整除网格大小的，例如：

```
width % gridX = 0
left % gridX = 0

height % gridY = 0
top % gridY = 0
```
