### ISSUE TITLE
组件失焦建议

### ISSUE THREAD

**Issue by jiangzetian** [vangleer/es-drager#27]
# 组件失焦建议
大佬您好，鼠标点击拖拽元素父组件外元素时，边框自动消失（失焦），能否提供失焦事件，和手动失/聚焦的相关操作。

**Comment by jiangzetian** [comment]
大佬nb，select确实可以控制选中和不选状态，但是（失焦）也会造成组件已选中，但是没有选中样式的情况，所以选中和失/聚焦直接的关系，还有一些优化空间，或者提供足够的自定义接口。

**Comment by vangleer** [comment]
可别再叫大佬了 🤦‍♂️，老铁 
你说的对，只要点击事件不冒泡到document就不会失焦。当时这么设计也是为了通用的原则
低代码可以自己控制select就行。后期会加上选择和不选的事件，但是感觉需要的场景不是很多
