### ISSUE TITLE
拖动位置跟踪异常、聚焦判定异常

### ISSUE THREAD

**Issue by itmanyong** [vangleer/es-drager#3]
- 1.拖动位置异常，如下图所示配置，10x10的网格中较为快速拖动方框，会出现方框停留位置与鼠标拖动位置出现较大差异
- 2.聚焦方框拖动过程中不松开情况下，进行截图操作(类似于qq截图那种静止蒙层状态)后松开鼠标左键，待取消截图状态后，无需聚焦，鼠标移动也会带动方框进行移动
![image](https://github.com/vangleer/es-drager/assets/53500371/977583e1-136d-4023-b468-e9ce2857fcd9)

**Comment by vangleer** [comment]
已修复，关一下issue哈
