### ISSUE TITLE
发现宽高缩放比是没有用的 还是可以随意缩放

### ISSUE THREAD

**Issue by caohuiboss** [vangleer/es-drager#35]
就是文档中有三个宽高缩放的相关属性 ，但是没有效果，打个比方，我这边想要16/9那么无论如何拖拽都是16/的比例才对，但是不行
scaleRatio | 缩放比 | ^[number] | 1
equalProportion | 宽高等比缩放 | ^[boolean]
aspectRatio | 宽高缩放比 | ^[boolean]

通过看源码我发，按住shift键是有用的，但是不按住shift只有equalProportion为true的时候拖拽八方点却无效
```
 (equalProportion || isShiftKey) && !aspectRatio
        ? rect.width / rect.height
        : aspectRatio
```

![image](https://github.com/vangleer/es-drager/assets/40628220/5543bfe1-9470-4e1a-a897-99c455c06f3f)

**Comment by vangleer** [comment]
你好，scaleRatio 是支持缩放比的，这个属性存在的条件是画布元素（也就是父元素）存在缩放才需要设置这个属性。
equalProportion: 是boolean类型，设置宽高等比缩放
aspectRatio: 是number类型，设置宽高缩放比例，按shift键进行缩放功能和equalProportion=true一样
例如:
```html
<template>
  <div class="editor" :style="{ transform: `scale(${scaleRatio})` }">
    <Drager
      :width="100"
      :height="100"
      :left="100"
      :top="100"
      :scaleRatio="scaleRatio"
      boundary
    >
      按钮
    </Drager>
  </div>

</template>

<script setup lang="ts">
import Drager from 'es-drager/index'
const scaleRatio = 0.5
</script>
<style>
.editor {
  position: relative;
  width: 1000px;
  height: 600px;
  background-color: #ccc;
}
</style>
```

![image](https://github.com/vangleer/es-drager/assets/45399976/60d4c0a3-5403-4dc2-bf3b-d5a7847eba84)

**Comment by vangleer** [comment]
文档 aspectRatio 的类型有误，应该是number类型，我们这边改一下

**Comment by caohuiboss** [comment]
> ```
> boundary
> ```

谢谢大佬解答，但是我这边期望的是 当我设置了某个属性的时候，能做到拖拽八个点和isShiftKey一样的效果，但是我试了不行

**Comment by vangleer** [comment]
equalProportion=true 就是实现这个效果的

**Comment by caohuiboss** [comment]
> equalProportion=true 就是实现这个效果的，这个属性和aspectRatio不要同时设置

![image](https://github.com/vangleer/es-drager/assets/40628220/305d4bd1-5370-4a93-82c4-1b9fe52da280)

大佬 我这边设置了 但是没有效果 还是可以随意缩放

**Comment by vangleer** [comment]
你的是哪个版本呐

**Comment by caohuiboss** [comment]
> 你的是哪个版本呐

我这边直接使用示例的demo，script引入的
```
<script src="https://unpkg.com/es-drager"></script>
```
查看到版本是这个 https://unpkg.com/es-drager@1.2.10/lib/index.umd.js

**Comment by vangleer** [comment]
不是单文件组件属性不能用驼峰哦
:scale-ratio="1.7"
:equal-proportion="true"

**Comment by caohuiboss** [comment]
> 不是单文件组件属性不能用驼峰哦 :scale-ratio="1.7" :equal-proportion="true"

我去，平时我这么写组件都ok的，谢谢大佬抽空解答，中划线没问题了Thanks♪(･ω･)ﾉ

**Comment by vangleer** [comment]
哈哈 我也是刚刚发现的

**Comment by caohuiboss** [comment]
> 哈哈 我也是刚刚发现的

不科学，可能是只有单文件组件是这样，项目里不这样

**Comment by vangleer** [comment]
是呢
