### ISSUE TITLE
是否添加动态计算宽高的属性

### ISSUE THREAD

**Issue by caohuiboss** [vangleer/es-drager#36]
观看demo的时候发现文本输入长度超过拖拽框的长度会超出去，是否可以有相关的属性将拖拽框根据里面的内容动态的长宽动态计算，从而将内容完全包裹

**Comment by vangleer** [comment]
这个可以设置css属性哈 `.es-drager { word-break: break-all; }`

**Comment by caohuiboss** [comment]
> 这个可以设置css属性哈 `.es-drager { word-break: break-all; }`

刚在编辑器demo实验了一下，好像是不行的，那个边框还是让文字内容出界了，我在想的是是否设置一个autoContent的属性，从而拖拽框可以自行根据内容撑开，同时框的width、height等这些值依旧是数值

![image](https://github.com/vangleer/es-drager/assets/40628220/9d8fbd4e-2cc4-4b4b-8f61-b851678c6d5b)

**Comment by vangleer** [comment]
这个需求有点超出es-drager这个组件的作用范围了，可能不会在es-drager组件内部支持哦。后期在编辑器会实现这个功能的

**Comment by caohuiboss** [comment]
> 这个需求有点超出es-drager这个组件的作用范围了，可能不会在es-drager组件内部支持哦。后期在编辑器会实现这个功能的

ok，那么大佬，对于这种的话有啥思路不，因为长宽不固定，然后文字有大有小行高可能又会换行啥的等等

**Comment by vangleer** [comment]
可以单独用一个标签包裹内容，在输入的时候获取内容的宽高，设置给es-drager就行了

**Comment by caohuiboss** [comment]
> 可以单独用一个标签包裹内容，在输入的时候获取内容的宽高，设置给es-drager就行了

![image](https://github.com/vangleer/es-drager/assets/40628220/cecced07-cc15-464c-a322-2f269c1baa51)
w我这边是这么写的，监听state.textContent的变化获取textLayerRef的宽高，总之试了蛮多方法的，取不出对应的宽高出来，感觉要根据文字的长短行高计算才行

**Comment by vangleer** [comment]
可以参考下这个
```html
<template>
  <Drager
    rotatable
    @dblclick="handleDbClick"
    @blur="handleBlur"
  >
    <TextEditor ref="textEditorRef" :editable="editable" text="文字" />
  </Drager>

</template>

<script setup lang="ts">
import { ref } from 'vue'
import Drager from 'es-drager/index'
import TextEditor from '@es-drager/editor/src/components/editor/TextEditor.vue'
const editable = ref(false)
const textEditorRef = ref()
function handleDbClick() {
  editable.value = true
  document.addEventListener('keydown', onKeydown)
}

function handleBlur() {
  editable.value = false
  document.removeEventListener('keydown', onKeydown)
}

function onKeydown() {
  console.log(textEditorRef.value?.el?.getBoundingClientRect())
}

</script>

<style>
.es-text {
  width: auto !important;
  height: auto !important;
}
</style>


```
