### ISSUE TITLE
框选结束以后 被选中的节点会失去selected属性

### ISSUE THREAD

**Issue by liangzai927** [vangleer/es-drager#37]
在框选节点之后 节点selected属性是true  但是没有selected属性
![image](https://github.com/vangleer/es-drager/assets/48548032/0820d0f3-e41e-4c66-9a06-4a958e162076)

**Comment by liangzai927** [comment]
在线案例的组合拆分里面也有这个bug

**Comment by vangleer** [comment]
selected属性不是双向绑定的，需要通过事件`focus/blur`重新赋值

**Comment by liangzai927** [comment]
暴露出来的blur和focus方法只会返回一个true/false 在focus/blur里面直接改变item的selected属性 没有效果啊

**Comment by liangzai927** [comment]
> 暴露出来的blur和focus方法只会返回一个true/false 在focus/blur里面直接改变item的selected属性 没有效果啊

没搞明白这两个方法是怎么用的🤦🏻‍♀️

**Comment by vangleer** [comment]
参考一下这个实例哈
```html
<template>
  {{ selected }}
  <button @click.stop="onFocus">选中</button>
  <button @click.stop="onBlur">取消选中</button>
  <Drager
    :width="100"
    :height="100"
    :left="100"
    :top="100"
    :selected="selected"
    rotatable
    @focus="onFocus"
    @blur="onBlur"
  >
    按钮
  </Drager>

</template>

<script setup lang="ts">
import { ref } from 'vue'
import Drager from 'es-drager/index'

const selected = ref(false)

const onFocus = () => selected.value = true

const onBlur = () => selected.value = false
</script>

```

**Comment by liangzai927** [comment]
> ```
> index
> ```

![image](https://github.com/vangleer/es-drager/assets/48548032/5ac9aeef-9071-4a2a-a799-8dbcb65b8ffb)
![image](https://github.com/vangleer/es-drager/assets/48548032/5675b489-a019-46eb-aefc-ee95c42c2cc3)
我是用的对象上的selected属性 在框选的时候会改变selected属性 会被选中 但是取消框选会触发blur方法 强请改为false

**Comment by liangzai927** [comment]
https://github.com/vangleer/es-drager/assets/48548032/1bd48af3-ba46-4fed-8264-ebc918e25c74

**Comment by liangzai927** [comment]
> Screen-2024-03-29-140202.mp4

这个是组分与拆分的组件 框选取消后 会触发blur这个方法 被选中的样式消失了 我在blur中改变item的selected属性没有用
但是在编辑器案例中 没有这个bug 我没研究出来是什么原因 希望大佬能解答一下

**Comment by vangleer** [comment]
给画布阻止一下点击冒泡就好了，因为点击事件冒泡到document就会自动失去焦点

![image](https://github.com/vangleer/es-drager/assets/45399976/a177a23a-704d-430b-8be2-5a21c9dd6d48)

**Comment by liangzai927** [comment]
> 给画布阻止一下点击冒泡就好了，因为点击事件冒泡到document就会自动失去焦点
> 
> ![image](https://private-user-images.githubusercontent.com/45399976/317970920-a177a23a-704d-430b-8be2-5a21c9dd6d48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2OTMzOTAsIm5iZiI6MTcxMTY5MzA5MCwicGF0aCI6Ii80NTM5OTk3Ni8zMTc5NzA5MjAtYTE3N2EyM2EtNzA0ZC00MzBiLThiZTItNWEyMWM5ZGQ2ZDQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDA2MTgxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhOTY0ZTZiZTRmZjdlZmM0ZmFjZjJhN2RlOGVkOWU0ZTIzMWFiNTRiZTNkY2FiY2QzN2NiODFhYTIyODI3ZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i1jD_C5qNAPg_UYdxNmQgnwQI6AsbY28Bl5WuLUYL1E)

感谢大佬 解决了 确实没想到是冒泡导致的🙏

**Comment by vangleer** [comment]
我的问题，编辑器发现的时候就改了，文档忘记更新了 😓

**Comment by Hobart-C** [comment]
> 我的问题，编辑器发现的时候就改了，文档忘记更新了 😓

还有个问题，框选完成之后，点击画布取消所有选中（看似没问题），但是将areaSelected设置为false的点击事件没有被触发，需要再点一下画布才会执行。以上这样的情况存在，所以会导致框选完成之后点击画布看似是取消了多选状态，但是依次点击drager时，还是多选状态，不会说选一个切一个

**Comment by Hobart-C** [comment]
> 给画布阻止一下点击冒泡就好了，因为点击事件冒泡到document就会自动失去焦点
> 
> ![image](https://private-user-images.githubusercontent.com/45399976/317970920-a177a23a-704d-430b-8be2-5a21c9dd6d48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyNzU2MjMsIm5iZiI6MTcyMTI3NTMyMywicGF0aCI6Ii80NTM5OTk3Ni8zMTc5NzA5MjAtYTE3N2EyM2EtNzA0ZC00MzBiLThiZTItNWEyMWM5ZGQ2ZDQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDA0MDIwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjYmRmNWExY2RiMWIxZWM3N2FmOGM1OGY4OGQyZjBmODJmZmIwZDMzOGVjZGUwY2JkMGQ4ZDI4ZDNkZDE1ZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R_eeCXL5gx5YnxRqXYpvv1Y710m72ir2C-MjyLyEtas)

可是你的代码里没有这个stop也没问题
