### ISSUE TITLE
等比缩放加上边界检测的问题

### ISSUE THREAD

**Issue by F-howk** [vangleer/es-drager#39]
当开启equalProportion 或者 aspectRatio  和 boundary 的时候 resize 右下角  当bottom 边先接触到边的时候继续拖拽 容易出现 宽高比错误 右边框 贴住父节点
（无旋转）

**Comment by F-howk** [comment]
大佬麻烦回复一下

**Comment by vangleer** [comment]
还在修复哈，前两天给忙忘了 😅

**Comment by F-howk** [comment]
感谢大佬
