### ISSUE TITLE
画布缩放状态下，拖拽元素会导致鼠标偏移

### ISSUE THREAD

**Issue by Blzaer** [vangleer/es-drager#4]
画布缩放状态下，拖拽元素会导致鼠标偏移，比如将背景画布的scale设置成2，再移动元素，鼠标位置会错乱。

**Comment by vangleer** [comment]
es-drager 有 scaleRatio 属性就是用来处理画布元素有缩放的情况的，scaleRatio 和画布比例保持一致即可。例如画布缩放2倍，scaleRatio=2

**Comment by Blzaer** [comment]
谢谢，已经解决！大佬牛批。还有一个问题，就是我看api里面没有禁止禁止拖动属性，是否可以加上

**Comment by vangleer** [comment]
有disabled属性可以禁止拖拽缩放旋转，默认样式是灰色的，你可用 `.es-drager.disabled` 类名修改样式哈

**Comment by Blzaer** [comment]
好的，解决了！如果集成了echart的话，我看到有个伪类作用在上面，导致鼠标移到图表不能显示echarts自带的数值tooltip数据。这个可以有属性来控制吗？

**Comment by vangleer** [comment]
这个问题确实存在，我这边改一下。你着急可以先手动设置一下 .es-drager:after { display: none; }

**Comment by Blzaer** [comment]
好嘞，我先自己处理一下！谢谢大佬。这个issue 先关闭了
