### ISSUE TITLE
如果需要保存并回显 useId方法会出现相同的id 

### ISSUE THREAD

**Issue by liangzai927** [vangleer/es-drager#41]
common.ts中的useId方法 默认是从1开始的 如果将画布保存 再次进入 还是会从1开始 会导致id重复 删除的时候会将最先匹配到的对应节点删除

我是用了个随机数 解决了 用uuid应该会更好一点
![image](https://github.com/vangleer/es-drager/assets/48548032/812d7657-dc38-43f5-9548-04021b707b42)

**Comment by vangleer** [comment]
确实有这种情况，后续会尽快改正，多谢指出
