### ISSUE TITLE
类型编辑，失去焦点等

### ISSUE THREAD

**Issue by RuoChengF** [vangleer/es-drager#43]
是否可以添加一个类型编辑的 参数呢？
1. 比如  是文本的话  拖拽到画布之后 是可以进行编辑操作的， 
这一点是否可以加一个 type 属性进行判断 当前元素是否可以进行文本编写
2. 失去焦点事件 ，不知为啥 我在使用时没有触发

**Comment by vangleer** [comment]
1. es-drager 组件主要的初衷时解决拖拽缩放等通用功能的，并没有实现编辑操作。可以根据自己的需求进行二次封装哈，编辑操作可以参考这个编辑器demo。https://vangleer.github.io/es-drager/#/editor
2. blur事件是用户点击其它区域或取消选中时才会触发的

**Comment by RuoChengF** [comment]
嗯嗯 已经在原有基础上实现了

---- 回复的原邮件 ----
| 发件人 | 幽月之格 Vange ***@***.***> |
| 发送日期 | 2024年06月25日 08:40 |
| 收件人 | vangleer/es-drager ***@***.***> |
| 抄送人 | RuoChengF ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [vangleer/es-drager] 类型编辑，失去焦点等 (Issue #43) |

es-drager 组件主要的初衷时解决拖拽缩放等通用功能的，并没有实现编辑操作。可以根据自己的需求进行二次封装哈，编辑操作可以参考这个编辑器demo。https://vangleer.github.io/es-drager/#/editor
blur事件是用户点击其它区域或取消选中时才会触发的

**Comment by vangleer** [comment]
好的 感谢理解
