### ISSUE TITLE
无法使用键盘事件监听吗？

### ISSUE THREAD

**Issue by RuoChengF** [vangleer/es-drager#45]
我在使用时， 想实现 按住shift  加点击的时候 来实现多选。 但是 没有响应 ， 是键盘事件拦截了吗 ？  @keydown.shift

**Comment by vangleer** [comment]
keydown事件建议给全局document加哈，如果按下了shift键就支持多选就行了

**Comment by RuoChengF** [comment]
嗯嗯 我全局加的， 大佬这个组件很牛 期待增加更多可选功能

---- 回复的原邮件 ----
| 发件人 | 幽月之格 Vange ***@***.***> |
| 发送日期 | 2024年07月04日 15:37 |
| 收件人 | vangleer/es-drager ***@***.***> |
| 抄送人 | RuoChengF ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [vangleer/es-drager] 无法使用键盘事件监听吗？ (Issue #45) |

keydown事件建议给全局document加哈，如果按下了shift键就支持多选就行了

**Comment by RuoChengF** [comment]
刚才提了一个issue 里面有个外层画布旋转 里面的画布内容在拖拽是对称移动， 我想到了解决办法， 让父之组件的旋转角度一致就行应该， 但是选中和禁用的问题没想明白

---- 回复的原邮件 ----
| 发件人 | 幽月之格 Vange ***@***.***> |
| 发送日期 | 2024年07月04日 16:55 |
| 收件人 | vangleer/es-drager ***@***.***> |
| 抄送人 | RuoChengF ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [vangleer/es-drager] 无法使用键盘事件监听吗？ (Issue #45) |

感谢支持哈，后期会慢慢完善

**Comment by vangleer** [comment]
对的，选中和禁用可以自己控制，如果禁用了就设置selected为false就行

**Comment by RuoChengF** [comment]
旋转的 我测试了 不可以，目前大佬有没有解决方案呢 嵌套的drager 组件， 最外层的旋转之后 再次推拽里面的drager里的元素 移动位置不对这个问题

---- 回复的原邮件 ----
| 发件人 | 幽月之格 Vange ***@***.***> |
| 发送日期 | 2024年07月05日 10:11 |
| 收件人 | vangleer/es-drager ***@***.***> |
| 抄送人 | RuoChengF ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [vangleer/es-drager] 无法使用键盘事件监听吗？ (Issue #45) |

对的，选中和禁用可以自己控制，如果禁用了就设置selected为false就行

**Comment by vangleer** [comment]
建议父元素旋转后子元素就禁止旋转。可以把子元素旋转完后再组合到父drager中，类似这种
![image](https://github.com/vangleer/es-drager/assets/45399976/d26a1653-8cdd-47df-8017-6fda0ddda794)

**Comment by RuoChengF** [comment]
好嘞 我思考一下

---- 回复的原邮件 ----
| 发件人 | 幽月之格 Vange ***@***.***> |
| 发送日期 | 2024年07月05日 10:49 |
| 收件人 | vangleer/es-drager ***@***.***> |
| 抄送人 | RuoChengF ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [vangleer/es-drager] 无法使用键盘事件监听吗？ (Issue #45) |

建议父元素旋转后子元素就禁止旋转。可以把子元素旋转完后再组合到父drager中，类似这种
image.png (view on web)

**Comment by hetianxiang** [comment]
点击编辑就取消选中了 你的编辑器是怎么做到还能在selected的状态的啊

**Comment by vangleer** [comment]
阻止编辑器点击冒泡就可以了
