### ISSUE TITLE
可以支持嵌套吗

### ISSUE THREAD

**Issue by jiaiqi** [vangleer/es-drager#50]
### 您希望添加的功能
拖拽支持嵌套
类似于这样 开发低代码编辑器会有这种场景，组件嵌套组件
![image](https://github.com/user-attachments/assets/392b3847-9dc4-4529-9776-b2460ebb5f1a)

**Comment by huccct** [comment]
好提议~

**Comment by vangleer** [comment]
目前提供了一个简单的嵌套方案，参考https://vangleer.github.io/es-drager/#/basic
