### ISSUE TITLE
是否可以在事件回调的参数中增加一个初始angle 用于判断是从顺时针旋转的还是从逆时针旋转的

### ISSUE THREAD

**Issue by qipengwei** [vangleer/es-drager#53]
### 您希望添加的功能

请详细描述您希望添加的功能。

### 为什么需要这个功能？

请解释为什么这个功能对您或其他用户有用。

### 其他上下文

请添加任何其他相关的上下文或截图。

**Comment by vangleer** [comment]
这个功能在可以在`rotate-start`，`rotate`，`rotate-end`事件中做哈，记录上一次的，然后和当前的对比就可以知道是顺时针还是逆时针了
