### ISSUE TITLE
作者您好，当前控件整体不支持自适应宽度

### ISSUE THREAD

**Issue by yangsanjin5** [vangleer/es-drager#54]
作者您好，当前控件整体不支持自适应宽度，希望后续控件能新增功能，按照一定比例自适应浏览器窗口宽度

**Comment by vangleer** [comment]
如果有这方面的需求，可以手动实现的，监听浏览器宽度缩放比，用缩放比计算每个元素的大小即可

**Comment by yangsanjin5** [comment]
好的 谢谢您
