### ISSUE TITLE
关于缩放

### ISSUE THREAD

**Issue by RuoChengF** [vangleer/es-drager#55]
目前按住shift 键是会进行等比缩放的， 但是如何实现不按住shift 在拖拽四个角的时候是等比缩放， 但是四个方向时仅做宽高修改呢 ？
参考网址 https://www.designkit.com/design/ 中的海报里面对元素的拖拽缩放

**Comment by vangleer** [comment]
可以使用 `equalProportion` 属性开启等比缩放哈

**Comment by RuoChengF** [comment]
equalProportion 开启等比缩放后 top left bottom right 四个点位在拖拽时 也是等比的， 期望是 top left bottom right 这是个点位拖拽时只改宽高， 四个角拖拽时可以等比缩放

---- 回复的原邮件 ----
| 发件人 | 幽月之格 Vange ***@***.***> |
| 发送日期 | 2024年09月04日 10:08 |
| 收件人 | vangleer/es-drager ***@***.***> |
| 抄送人 | RuoChengF ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [vangleer/es-drager] 关于缩放 (Issue #55) |

可以使用 equalProportion 属性开启等比缩放哈

**Comment by RuoChengF** [comment]
或者有没有什么方法可以监听到我点击的是哪个点位


---- 回复的原邮件 ----
| 发件人 | 幽月之格 Vange ***@***.***> |
| 发送日期 | 2024年09月04日 10:08 |
| 收件人 | vangleer/es-drager ***@***.***> |
| 抄送人 | RuoChengF ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [vangleer/es-drager] 关于缩放 (Issue #55) |

可以使用 equalProportion 属性开启等比缩放哈

**Comment by vangleer** [comment]
可以通过`resize` 插槽的方式获取到是哪个方向
```html
<template #resize="{ side }">
  <div class="custom-resize"></div>
</template>
```
