### ISSUE TITLE
是否可以新增一个配置项，禁止拖动呢？

### ISSUE THREAD

**Issue by qipengwei** [vangleer/es-drager#56]
### 您希望添加的功能

请详细描述您希望添加的功能。

### 为什么需要这个功能？

请解释为什么这个功能对您或其他用户有用。

### 其他上下文

请添加任何其他相关的上下文或截图。

**Comment by vangleer** [comment]
`disbaled` 属性就可以哈

**Comment by qipengwei** [comment]
> `disbaled` 属性就可以哈

不行的 disaaled会多出透明度的样式

**Comment by qipengwei** [comment]
> `disbaled` 属性就可以哈

.es-drager.disabled {
    cursor: default !important;
    opacity: 1 !important;
}  我把样式重写了 --
