### ISSUE TITLE
动态修改 height，无法监听到 height 变化

### ISSUE THREAD

**Issue by luxiangqiang** [vangleer/es-drager#57]
### 描述错误

当我动态的修改 :height="height" 中的 height 时，drager 高度无变化。

### 重现步骤

动态的改变 height 一下。

### 预期行为

drager 高度会随着 height 动态的变化。

### 截图

![image](https://github.com/user-attachments/assets/eaeb6f05-426f-43b9-a0a2-9708d66759e8)

我能确保 itemB 是响应式的，值已经确保改变了。

### 环境信息

- 操作系统: [e.g. mac ]
- 浏览器: [e.g. Chrome 79]
- 其他信息:

### 其他上下文

watch(
  () => [props.width, props.height, props.left, props.top, props.angle],
  ([width, height, left, top, angle], [oldWidth, oldHeight, oldLeft, oldTop, oldAngle]) => {
    if (width !== oldWidth) {
      dragData.value.width = width
    }
    if (height !== oldHeight) {
      dragData.value.height = height
    }
    if (left !== oldLeft) {
      dragData.value.left = left
    }
    if (top !== oldTop) {
      dragData.value.top = top
    }
    if (angle !== oldAngle) {
      dragData.value.angle = angle
    }
  }
)

watch(
  () => dragData.value,
  (val) => {
    emit('change', { ...val })
  },
  { deep: true }
)

当我动态的改变 :height 时，在监听的 @change 中 val 返回的 height 还是初始值。

目前猜测：

1、动态改变 :height prop 时，第一个 watch 函数（监听 props）被触发。
2、这个函数更新了 dragData.value.height。
3、然后第二个 watch 函数（监听 dragData.value）被触发。
4、然而，由于 Vue 为了性能会批量更新，第二个 watch 函数中的 emit('change', { ...val }) 可能在 dragData.value 更新新的高度之前被调用。

**Comment by luxiangqiang** [comment]
两个 watch 可能在同一更新周期内执行，可能导致第二个 watch 在 dragData.value 实际更新之前就被调用了。

**Comment by vangleer** [comment]
width，height，left，top 这些属性是单向的，需要监听change事件得到最新的位置信息赋值给itemB即可

**Comment by luxiangqiang** [comment]
> width，height，left，top 这些属性是单向的，需要监听change事件得到最新的位置信息赋值给itemB即可

我已经在 onResize (横向缩放的时候)里动态的去改变了 itemB.height 的值，我为何还要在 change 中改变 itemB.height 呢？

**Comment by luxiangqiang** [comment]
> > width，height，left，top 这些属性是单向的，需要监听change事件得到最新的位置信息赋值给itemB即可
> 
> 我已经在 onResize (横向缩放的时候)里动态的去改变了 itemB.height 的值，我为何还要在 change 中改变 itemB.height 呢？

正常的操作就是我动态改变了 itemB.height 的值，你的组件高度会随着这个值的大小而改变才对，每次 change 出来的高度值，都是我更新之前的值，并不是最新的值。

**Comment by luxiangqiang** [comment]
> > > width，height，left，top 这些属性是单向的，需要监听change事件得到最新的位置信息赋值给itemB即可
> > 
> > 
> > 我已经在 onResize (横向缩放的时候)里动态的去改变了 itemB.height 的值，我为何还要在 change 中改变 itemB.height 呢？
> 
> 正常的操作就是我动态改变了 itemB.height 的值，你的组件高度会随着这个值的大小而改变才对，每次 change 出来的高度值，都是我更新之前的值，并不是最新的值。

<img width="532" alt="image" src="https://github.com/user-attachments/assets/01120fa4-b682-47b2-b1d6-2509436fcb76">
看我打印的 log 日志，onResize 中我动态改变 itemB.height 值，change 中打印 dragData.height 的值，其中只有两次打印的正确，其他的 change 打印的值都是我初始化的值 71.72 ，所以很奇怪，而且视图中的高度也没有更新。

**Comment by luxiangqiang** [comment]
> width，height，left，top 这些属性是单向的，需要监听change事件得到最新的位置信息赋值给itemB即可

你直接监听 props 中的 width，height，left，top 然后更新视图中的样式不就可以了，为何还要借助 dragerData + watch 的方式间接更新呢？

**Comment by vangleer** [comment]
如果itemB是响应式的修改高度就没问题
```html
<template>
  <el-button @click="handleChangeSize(list[1])">修改高度</el-button>
  <Drager
    v-for="item in list"
    v-bind="item"
    @resize="onChange(item, $event)"
  >{{ item.height }}</Drager>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import Drager from 'es-drager/index'

const list = ref([
  { left: 100, top: 100, width: 100, height: 100 },
  { left: 200, top: 200, width: 100, height: 100 },
])

function handleChangeSize(item: any) {
  item.height = 200
}

function onChange(item: any, data: any) {
  Object.keys(item).forEach(key => {
    item[key] = data[key]
  })
}
</script>

```

![image](https://github.com/user-attachments/assets/62854237-9daf-4577-b149-453e1323e994)

**Comment by luxiangqiang** [comment]
> 如果itemB是响应式的修改高度就没问题
> 
> ```
> <template>
>   <el-button @click="handleChangeSize(list[1])">修改高度</el-button>
>   <Drager
>     v-for="item in list"
>     v-bind="item"
>     @resize="onChange(item, $event)"
>   >{{ item.height }}</Drager>
> </template>
> 
> <script setup lang="ts">
> import { ref } from 'vue'
> import Drager from 'es-drager/index'
> 
> const list = ref([
>   { left: 100, top: 100, width: 100, height: 100 },
>   { left: 200, top: 200, width: 100, height: 100 },
> ])
> 
> function handleChangeSize(item: any) {
>   item.height = 200
> }
> 
> function onChange(item: any, data: any) {
>   Object.keys(item).forEach(key => {
>     item[key] = data[key]
>   })
> }
> </script>
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/45399976/365501230-62854237-9daf-4577-b149-453e1323e994.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NTk2MDUsIm5iZiI6MTcyNTg1OTMwNSwicGF0aCI6Ii80NTM5OTk3Ni8zNjU1MDEyMzAtNjI4NTQyMzctOWRhZi00NTc3LWIxNDktNDUzZTEzMjNlOTk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDA1MjE0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwMWE2YmY3ODExNzUzOGQyNTJiZTBjMjc5NDIyNDY0MzFlZDk2NGUyNjRlZWUyMzgzZThhYTU2MjI5ZTA2MjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.E19UATL0_0w0fJaZlanx9FSWTswNlGAjheDqy3GTV44)

<template>
  <div class="container">
    <Drager v-for="item in list" v-bind="item" @resize="onResize(item, $event)" @change="onChange(item, $event)">{{ item.height }}</Drager>
  </div>
</template>

<script setup lang="ts">
import { nextTick, ref } from 'vue'
import 'es-drager/lib/style.css'
import Drager from 'es-drager'

const list = ref([
  { left: 100, top: 100, width: 100, height: 100 },
  { left: 200, top: 200, width: 100, height: 100 }
])

let count = 1

const onResize = (item: any, data: any) => {
  console.error(item.width, data.height)
  // 这里我要做动态改变高度 每次一次的值都不一样，这里暂时固定是 200 界面的元素就会闪烁
  item.height = 200
}

function onChange(item: any, data: any) {
  console.log('height', item.height)
  Object.keys(item).forEach((key) => {
    item[key] = data[key]
  })
}
</script>

<style>
.container {
  padding: 50px;
}
</style>


你试试我这个吧，横向拖拽这个地方，change出来的高度值一直是初始值，即使我已经动态调整过了。

<img width="656" alt="image" src="https://github.com/user-attachments/assets/f1584464-15e0-4289-8208-a573269370ba">

**Comment by vangleer** [comment]
你说的这个问题确实存在，resize的时候，鼠标按下就把当前的width和height备份了，后面进行缩放的时候都是用的这个备份去计算的，所以会有闪烁的情况

**Comment by luxiangqiang** [comment]
> 你说的这个问题确实存在，resize的时候，鼠标按下就把当前的width和height备份了，后面进行缩放的时候都是用的这个备份去计算的，所以会有闪烁的情况

你那边有空方便改吗？我现在项目中好几个地方 change 出来的值都不是最新的。

**Comment by vangleer** [comment]
我在想什么情况下会有在移动或缩放的时候去手动修改大小的，这种需求不常见啊

**Comment by luxiangqiang** [comment]
> 我在想什么情况下会有在移动或缩放的时候去手动修改大小的，这种需求不常见啊
我现在是在搞文本元素换行，需要高度动态根据文本高度变化，让高度始终包含文字

**Comment by vangleer** [comment]
好的，我们这边有空看一下哈

**Comment by vangleer** [comment]
可以用新增的文字类型哈 `type='text'`
