### ISSUE TITLE
对角线等比缩放问题

### ISSUE THREAD

**Issue by luxiangqiang** [vangleer/es-drager#59]
### 您希望添加的功能

当我锁定比例，对角线等比缩放的时候，鼠标垂直方向移动会等比缩放，鼠标水平方向不会等比缩放，交互体验差。（对比了其他框架，都是水平移动鼠标进行等比缩放，垂直移动鼠标不会等比缩放）

**Comment by luxiangqiang** [comment]
提交了一个PR速度啊 哥们 不行我就自己搞个仓库 发 npm 了

**Comment by vangleer** [comment]
sorry，最近有点忙 :facepalm: 刚刚看了下你改后缩放有点问题。左上和右上进行等比缩放时的方向不对

**Comment by luxiangqiang** [comment]
我测试过了 没问题

**Comment by luxiangqiang** [comment]
好的 我改一下
