### ISSUE TITLE
鼠标MouseDown事件存在一个问题

### ISSUE THREAD

**Issue by vannvan** [vangleer/es-drager#6]
目前鼠标事件没有区分单个按键还是多个按键，

按道理对于所有操作而言，应该是**单个**按键按下时才能进行后续的事件

目前具体的表现是，当在目标元素上 同时按下两个鼠标按键时也会触发后续的动作

可以参考以下文档

> https://developer.mozilla.org/zh-CN/docs/Web/API/MouseEvent/button

**Comment by vangleer** [comment]
good question my friend ! 👍

**Comment by vangleer** [comment]
问题已解决，我关了哈
