### ISSUE TITLE
上传一张图片然后缩小，在把其他对象置顶，图片会还原到原始大小

### ISSUE THREAD

**Issue by cbqqkcel** [vangleer/es-drager#63]
### 描述错误

请清晰简洁地描述错误是什么。

### 重现步骤

重现行为的步骤：

1. 去 '...'
2. 点击 '....'
3. 滚动到 '....'
4. 看到错误

### 预期行为

请清晰简洁地描述您期望发生的事情。

### 截图

如果适用，请添加屏幕截图以帮助解释您的问题。

### 环境信息

- 操作系统: [e.g. Windows 10]
- 浏览器: [e.g. Chrome 79]
- 其他信息:

### 其他上下文

请添加有关问题的任何其他上下文。

**Comment by vangleer** [comment]
请问一下您那边是怎么复现的

**Comment by cbqqkcel** [comment]
![动画](https://github.com/user-attachments/assets/233780b2-6825-443f-b8ad-afb18c27da71)
