### ISSUE TITLE
rotate插槽的旋转事件作用的dom范围能不能交给外面控制

### ISSUE THREAD

**Issue by qipengwei** [vangleer/es-drager#65]
### 您希望添加的功能

请详细描述您希望添加的功能。
我有个需求是旋转按钮旁边加一个删除按钮 放在rotate插槽里 但是因为旋转事件作用范围太大了  经常误触
### 为什么需要这个功能？

请解释为什么这个功能对您或其他用户有用。

### 其他上下文

请添加任何其他相关的上下文或截图。

**Comment by vangleer** [comment]
这个问题可以给删除按钮加个阻止mousedown事件冒泡解决哈

**Comment by qipengwei** [comment]
> 这个问题可以给删除按钮加个阻止mousedown事件冒泡解决哈

不行哦  我使用stopPropagation方法阻止冒泡了 但是还会触发
