### ISSUE TITLE
建议将元素移动全部用 transform 代替，提高性能优化

### ISSUE THREAD

**Issue by luxiangqiang** [vangleer/es-drager#66]
现在我项目中用到了这个库，当渲染多个元素的时候，尤其是大量元素的时候，频繁的移动就会导致重拍和重绘。

**Comment by luxiangqiang** [comment]
> 确实 多个同时拖动的时候会比较卡

我单独搞了一个库，很多优化，自己发了一个 npm 包 具体看着：https://www.npmjs.com/package/es-drager-vue3

**Comment by wuhuiwa** [comment]
> > 确实 多个同时拖动的时候会比较卡
> 
> 我单独搞了一个库，很多优化，自己发了一个 npm 包 具体看着：https://www.npmjs.com/package/es-drager-vue3

能把优化过的库开源一下吗，借鉴一下你的优化思路
