### ISSUE TITLE
新增鼠标滚轮缩放画布功能

### ISSUE THREAD

**Issue by shawyawen** [vangleer/es-drager#68]
### 您希望添加的功能
新增鼠标滚轮缩放画布功能

### 为什么需要这个功能？
优化使用体验

### 代码优化
1、useActions文件加入以下代码
// 鼠标滚动
  const onWheel = (e: WheelEvent, item: ComponentType) => {
    e.preventDefault();

    const { deltaY } = e;
    let scale = data.value.container.scaleRatio;
    // 根据滚轮方向调整缩放比例
    if (deltaY < 0) {
      scale += 0.1; // 向上滚动，放大
    } else {
      scale -= 0.1; // 向下滚动，缩小
    }

    // 确保缩放比例在合理范围内
    if (scale < 0.5) {
      scale = 0.5;
    } else if (scale > 2) {
      scale = 2;
    }

    // 应用缩放样式
    data.value.container.scaleRatio = scale;
  };`
![image](https://github.com/user-attachments/assets/9958e410-040c-41db-90ec-5013291a5766)

2、editor\index文件绑定鼠标滚动事件：
![image](https://github.com/user-attachments/assets/ea02a42e-f16c-442a-826b-791c0e470a2f)
![image](https://github.com/user-attachments/assets/de7a07d1-cb1a-4787-b94f-a795271c2db0)

3、EditorStyle文件改造scaleRatio：
`const scaleRatio = computed({
  get: () => {
    return Math.round(store.data.container.scaleRatio * 100);
  },
  set: () => {
    store.data.container.scaleRatio = Math.round(
      store.data.container.scaleRatio / 100
    );
  },
});`
![image](https://github.com/user-attachments/assets/70d67b1d-0332-41f0-b2ba-271e5740f64e)

**Comment by shawyawen** [comment]
这个已经处理了，缩放按住ctrl+滚动

**Comment by vangleer** [comment]
> 这个已经处理了，缩放按住ctrl+滚动

好的，幸苦 👍
