### ISSUE TITLE
ES Drager Editor编辑器，在画布中修改文本，右边配置属性中的文本不能同步生效

### ISSUE THREAD

**Issue by shawyawen** [vangleer/es-drager#69]
### 描述错误
ES Drager Editor编辑器，在画布中双击修改文本，右边配置属性中的文本不能同步生效

### 预期行为
保持数据一致性

### 截图
![image](https://github.com/user-attachments/assets/c84a8295-b9f3-4ee4-90bf-bb5b267defe5)

### 解决方案
双向绑定text
1、editor\index.vue文件
把TextEditor组件上的:text改为v-model:text

`<TextEditor
            v-if="item.text"
            :editable="item.editable"
            v-model:text="item.text"
            :style="pickStyle(item.style)"
          />
`
![image](https://github.com/user-attachments/assets/ab5ffbd9-9a8a-4211-a5e5-22e81c811171)

2、TextEditor加上双向绑定代码，是去焦点的时候更新text数据
`<template>
  <div
    ref="textRef"
    :class="['es-text', { editable }]"
    :contenteditable="editable"
    @blur="textBlur"
  >
    {{ text }}
  </div>
</template>

/** text文本 双向绑定 */
const emit = defineEmits(["update:text"]);
const textBlur = (e) => {
  const val = e.target.innerText;
  emit("update:text", val);
};`

![image](https://github.com/user-attachments/assets/6459a12e-a92a-4e0c-8066-4e4e3c036c83)

**Comment by vangleer** [comment]
铁子，我看这几个issue你都提了解决方案，方便可以提个pr哈

**Comment by shawyawen** [comment]
> 铁子，我看这几个issue你都提了解决方案，方便可以提个pr哈

提交被拒了

**Comment by vangleer** [comment]
没见你提的记录呢

**Comment by shawyawen** [comment]
![image](https://github.com/user-attachments/assets/f44ddc41-490f-4a1e-9a46-0e57961d5fb6)
提交不上去

**Comment by vangleer** [comment]
不是这么提的哦！
先把这个仓库folk到你github账号里，然后再clone到你本地开发（尽量在dev分支下开发）
开发完后提交到你的github上，在github上发起Pull request
可以先了解一下Pull request 流程哈
