### ISSUE TITLE
有提供碰撞检查功能嘛？

### ISSUE THREAD

**Issue by momtboy** [vangleer/es-drager#8]
类似这样的功能
[https://gausszhou.github.io/vue3-drag-resize-rotate/#/advanced/advanced-conflict-detection](https://gausszhou.github.io/vue3-drag-resize-rotate/#/advanced/advanced-conflict-detection)

**Comment by vangleer** [comment]
目前没有，后期可能会支持

**Comment by vangleer** [comment]
使用 checkCollision 控制是否开启碰撞检测功能哈
